# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8984e991f06823f7a20bab6f185b050685ba37a34555c025a03efe1ae9bdac91bbe3ed41b35fe77d38e3d8ab4705b36570758303cbb369e18bb59779cc313a

test:
  secret_key_base: f9fdc8c047b8b6398b3a37e628da448140f49426a033e6b7cbfd3cf0783219dafa097a792e725398bd8fa32f48fc0eb81729353fa88f73c0f80ff5c2e3d6645c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
